### ISSUE TITLE
Error generating video Error: Failed to generate play. Status Code: 999

### ISSUE THREAD

**Issue by zqr-star** [DanfordGidraph/chat-gpt-video-maker#2]
what is the problem? Here is the detail    
           
[Axios Logger][Request] 13:15:48 POST https://api.openai.com/v1/chat/completions
[Axios Logger][Error] 13:16:09 POST https://api.openai.com/v1/chat/completions
Error generating video Error: Failed to generate play. Status Code: 999
    at C:\chat-gpt-video-maker-main\chat-gpt-video-maker-main\src\utils\StoryGenerator\index.js:31:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by DanfordGidraph** [comment]
Hi, have you followed the instructions for setting up your environment?

![Screenshot_20241023_094334_GitHub.jpg](https://github.com/user-attachments/assets/e2e7517b-096f-4e70-8827-a6cab2ff0dec)

If you follow the instructions outlined in the README paying attention to above section then it should work. An OpenAI API key must be added in the `.env` file

**Comment by zqr-star** [comment]
{
    "error": {
        "message": "You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}

**Comment by DanfordGidraph** [comment]
Please follow the instructions as directed. 
1. Create a file called `.env` in the root of your project
2. Copy over all the values in the `.env.example` file to this file. 
3. Add your OpenAI API key (Obtained as shown here [How To Get Your Own OpenAI API Key](https://medium.com/@lorenzozar/how-to-get-your-own-openai-api-key-f4d44e60c327)) to the field called `OPENAI_API_KEY` 
4. Run the app as instructed.
Here is a screenshot of what your `.env` file should contain.
![image](https://github.com/user-attachments/assets/4c41c5d1-e428-4fbc-ac81-369141da4c0e)
If you don't know how to work with project-level environment variables please take a read of this wonderful post: [Node.js Everywhere with Environment Variables](https://medium.com/the-node-js-collection/making-your-node-js-work-everywhere-with-environment-variables-2da8cdf6e786)
